onbox_version: 0.1.2
default_table_size: 10
show_file_accordion: true
yui_path: /yui
  
development:
  domain: localhost:3000
  poster_storage: /tmp/OnBoxPosters/

test:
  domain: test.host
  yui_path: http://yui.yahooapis.com/2.8.0r4/build
  poster_storage: /tmp/
  
cucumber:
  domain: localhost:3000
  poster_storage: /tmp/
  show_file_accordion: false

production:
  domain: video.cavenagh.org
  poster_storage: /media/content/Sam/OnBoxImgs/
