development:
  domain: localhost:3000
  yui_path: /yui
  poster_storage: /Volumes/Other/OnBoxPosters/
  default_table_size: 10

test:
  domain: test.host
  yui_path: http://yui.yahooapis.com/2.8.0r4/build
  poster_storage: /tmp/
  default_table_size: 10 
  
cucumber:
  domain: localhost:3000
  yui_path: /yui
  poster_storage: /tmp/
  default_table_size: 10

production:
  domain: dub:3000
  yui_path: /yui
  poster_storage: /media/content/Sam/OnBoxImgs/
  default_table_size: 10  
